### PR TITLE
Added editorconfig

### PR DESCRIPTION
**Pull request by KOLANICH**
Automatically solves some issues rejected by ci.py script at edit time in the editors with the plugin installed or builtin support.

### CODE REVIEW

**Comment by jhasse** [comment]
`end_of_line = lf` is missing ;)

**Comment by KOLANICH** [comment]
My bad. Thanks, now it is fixed.

**Comment by jhasse** [comment]
You need to use those line endings in `.editorconfig`. Also please use imperative mood in the commit message (i.e. Add instead of Added).

**Comment by KOLANICH** [comment]
@jhasse

**Comment by jhasse** [comment]
Please no Markdown in the commit message's title.

**Pull request merged**
