### PR TITLE
[clang-tidy] fix inconsistent declarations

### PR DESCRIPTION
**Pull request by neheb**
Found with readability-inconsistent-declaration-parameter-name

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by jonesmz** [comment]
I would prefer that the name of the variable stay "target", and the definition of the function be changed from "node" to "target".

**Comment by neheb** [comment]
Rebased.

**Comment by jhasse** [comment]
Can you add `readability-inconsistent-declaration-parameter-name` to .clang-tidy?

**Comment by neheb** [comment]
Done,

**Pull request merged**
