### PR TITLE
Added CPack packaging

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by jonesmz** [comment]
Ninja is not currently suitable for use as a library. I don't see how changing libninja from a static library to a shared library is an improvement.

**Comment by KOLANICH** [comment]
It allows to update 2 parts separately.

**Comment by KOLANICH** [comment]
@jhasse

**Comment by jhasse** [comment]
What is the need for CPack? Isn't there a debian package for ninja already? I doubt that they are using CPack.

> It allows to update 2 parts separately.

Wouldn't both files be in the same package anyway?

Maybe creating an issue first would be a good idea. This adds a lot of code to the CMakeLists.txt, I'm a bit hesitant in merging without having a use for it. Sorry for closing this PR for now.

**Comment by KOLANICH** [comment]
>What is the need for CPack? Isn't there a debian package for ninja already? I doubt that they are using CPack.

I don't care how they use it. It doesn't matter. What matters is that an end user should be able to fetch this repo and build the bleeding edge package and install it. Without any `debhelper`s.

>Wouldn't both files be in the same package anyway?

It is adjustable using `SEPARATE_LIBNINJA`.

**Pull request closed without merging**
