### PR TITLE
Pass location of build.ninja file to browse script

### PR DESCRIPTION
**Pull request by colincross**
Pass the values of -f and -C arguments to the browse python script so
they can be passed back to ninja -t query.

### CODE REVIEW

**Comment by colincross** [comment]
Fixes #373

**Comment by nico** [comment]
`ninja -C out/Release/ -t browse base` seems to work fine for me already. ninja processes -C and then the subninja running in browse already has that as it's cwd. Why is that part needed?

**Comment by colincross** [comment]
I'll remove it.

**Comment by colincross** [comment]
-C argument removed, and tested that it still works.

**Comment by nico** [comment]
Looks good after resolving conflicts, thanks!

**Comment by colincross** [comment]
Rebased

**Comment by nico** [comment]
Thanks!

**Pull request merged**
