### PR TITLE
fix appveyor.yml

### PR DESCRIPTION
**Pull request by goshhhy**
ampersands need to be escaped.

this should fix appveyor.yml - leaving in draft until confirmed

### CODE REVIEW

**Comment by goshhhy** [comment]
this fixes #1611

if you run into issues involving sed in this project in the future, please feel free to mention me and i can take a look

**Comment by goshhhy** [comment]
this fixes #1611

if you run into issues involving sed in this project in the future, please feel free to mention me and i can take a look

**Comment by goshhhy** [comment]
(please feel free to squash the commits, and apologies for the noise as i tested this)

**Comment by jonesmz** [comment]
@goshhhy 

By the way, do you have any insights into how the continuous integration configuration failed without being changed?

Did AppVeyor change something in their environment?

**Comment by goshhhy** [comment]
i'm not sure how it could've worked in the first place, honestly. it should have been failing the whole time

my best guess would be something got changed about configure.py that had previously surreptitiously allowed it to build but later revealed the existing problem, but i don't know the commit history and where this actually started

**Comment by jonesmz** [comment]
Interesting insights. Thanks!

**Pull request merged**
