### PR TITLE
Remove 'using namespace std', properly namespace all std symbols

### PR DESCRIPTION
**Pull request by jonesmz**
Rip the band-aide off.

Methodology:

Remove all lines of "using namespace std;"
compile; while(not compiled) { paste std:: in front of the offending symbols; compile; }

### CODE REVIEW

**Comment by jhasse** [comment]
Where's the difference between this and #1862? (besides rebased on master)

**Comment by jonesmz** [comment]
6 months.

**Comment by jhasse** [comment]
So nothing, okay.

**Comment by jonesmz** [comment]
It's been almost a year since I opened this PR, and nearly a year and a half since the previous one was opened and then promptly closed.

It takes well over an hour to rebase this change.

Please stop being disrespectful of my time and either:

1. Merge it.
2. Give me a complete list of PRs that you want me to rebase on top of this PR, which I will promptly do.
3. Give me a comprehensive roadmap of which files, in which order, this change should be made in, so that I can open the appropriate pull requests.

As I've said before, this is the first change in a large series of patches, and not merging it causes me quite a lot of extra work.

**Comment by jonesmz** [comment]
Rebased on https://github.com/ninja-build/ninja/pull/2089

**Comment by jhasse** [comment]
Until there's a strong reason to do this on the whole codebase, I prefer the current way of doing it step by step in new code and touched lines.

**Pull request closed without merging**
