### PR TITLE
CMake: Use static MSVC runtime, fixes #1692

### LINKED ISSUE #1692: GitHub Actions: Statically link Visual C++ runtime
This will result in a bigger binary but no dependency on the VCRuntime installer.

### PR DESCRIPTION
**Pull request by jhasse**
See https://github.com/ninja-build/ninja/pull/1705#issuecomment-562972980

### CODE REVIEW

**Comment by crondog** [comment]
You should be able to set a variable which applies to all targets

`set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")`

https://cmake.org/cmake/help/v3.15/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html

**Comment by jhasse** [comment]
Didn't work in my tests. Anything I'm missing? Did it work for you?

**Comment by crondog** [comment]
I tested with the following change (based of master)
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e9f6563..061dc45 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,4 +1,5 @@
-cmake_minimum_required(VERSION 3.12)
+cmake_minimum_required(VERSION 3.15)
+cmake_policy(SET CMP0091 NEW)
 project(ninja)

 if(CMAKE_BUILD_TYPE MATCHES "Release")
@@ -15,6 +16,7 @@ if(CMAKE_BUILD_TYPE MATCHES "Release")
 endif()

 if(MSVC)
+  set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W4 /GR- /Zc:__cplusplus")
 else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated -fdiagnostics-color")

```

Which produces (which is the same output as your PR)
```
C:\code\ninja\build>dumpbin /DEPENDENTS ninja.exe
Microsoft (R) COFF/PE Dumper Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file ninja.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll

  Summary

        3000 .data
        5000 .pdata
       24000 .rdata
        1000 .reloc
        1000 .rsrc
       64000 .text

```

**Comment by jhasse** [comment]
Thanks! I thought I did exactly that in my testing, but I must have messed up somehow.

**Pull request merged**
