### PR TITLE
CanonicalizePath: fix 'a/b/.._foo' -> 'a'  replacement

### PR DESCRIPTION
**Pull request by paboldin**

### CODE REVIEW

**Comment by digit-google** [comment]
Thank you, the change looks good. Can you add a unit-test to util_test.cc to ensure we never regress in the future if we change this function?

**Comment by paboldin** [comment]
Thanks for the feedback! Updated.

**Comment by paboldin** [comment]
Can you please take a look at this once again?

**Comment by digit-google** [comment]
Thank you, this looks good to me. The Windows/x64 failures seems to be a flake when downloading re2c. Not sure how to work around this? @jhasse do you have an idea?

**Comment by jhasse** [comment]
Wait a few hours and then restart CI :)

**Pull request merged**
