### PR TITLE
check setvbuf() return-value

### PR DESCRIPTION
**Pull request by wilhelmtell**
`setvbuf()` returns a non-zero integer value on error. check for that, and report any error.

### CODE REVIEW

**Comment by wilhelmtell** [comment]
I wasn't entirely sure how to handle the error cases here. What do you think of calling `Error()`, and of the error strings?

**Comment by nico** [comment]
I think most places that check "this really shouldn't fail" function results call Fatal() instead of Error(). Are you seeing this function fail for you, or are you adding these checks mostly for hygienic reasons? If it's for hygiene, I'd make this call Fatal().

**Comment by wilhelmtell** [comment]
> Are you seeing this function fail for you, or are you adding these checks mostly for hygienic reasons?

I'm not sure I know what you mean by that. I haven't experienced this triggering, no. I found a function call that can fail, and added a check for that.

**Comment by wilhelmtell** [comment]
Alright, thanks @nico. I pushed an update, s/error/fatal/.

**Pull request closed without merging**
