### PR TITLE
C++11: Use range based for loops where practical

### PR DESCRIPTION
**Pull request by jonesmz**
This is the first of 6 patches for ninja from the [Splinter](https://github.com/splinter-build/splinter) project which depend on C++11.

Now that C++11 is enabled on all platforms, I propose this patch to be merged into the ninja code, allowing contributors to have a much more understandable and modern codebase.

While I would have preferred to see https://github.com/ninja-build/ninja/pull/1958 merged first (Editing this PR to not explicitly depend on [1958](https://github.com/ninja-build/ninja/pull/1958) took a good 40 minutes...), I've been waiting years for https://github.com/ninja-build/ninja/pull/1958 to be merged.

I won't open a PR for any of my other C++11 patches at this time, as removing their dependency relationship on each other would be more time than I have available currently.

Ideally this PR will be merged promptly so that the next patch can be taken as-is.

### CODE REVIEW

**Comment by jhasse** [comment]
IMHO the disadvantages outweigh the advantages, sorry. See our previous discussions.

Please open an issue or write to the mailing list before creating a new PR about this.

**Comment by jonesmz** [comment]
What disadvantages? I can't address them if you don't bring them to my attention.

As far as I know, you and I have never discussed C++11 range based for loops.

But now C++11 is enabled for all platforms and build types, so nothing prevents this from being merged other than possibly minor conflicts with other pull requests.

> Please open an issue or write to the mailing list before creating a new PR about this.

Stop closing pull requests just because you have a personal disagreement with them. There are clearly other people who are interested in seeing C++11 features used in the codebase beyond just myself.

There's no point in making an issue if I already have the associated code changes. A pull request is simply an issue+codechanges+CI results. Making an issue without the already-existing code changes is a reduction in usability.

**Comment by jhasse** [comment]
> As far as I know, you and I have never discussed C++11 range based for loops.

I mean C++11-fying old code.

> There's no point in making an issue if I already have the associated code changes. A pull request is simply an issue+codechanges+CI results. Making an issue without the already-existing code changes is a reduction in usability.

I disagree. IMHO the number of stale PRs should be kept low and discussions about undecided things should be done in issues (e.g. "Should we change all for loops to C++11-style for each loops?") and discussions about specific changes should be done in PRs (e.g. "Should we move these lines into a function?").

**Comment by jonesmz** [comment]
This is not a stale PR. It had no conflicts with the current master branch as of yesterday, and I've kept it up to date any time something was merged that caused a conflict.

There's no discussion to be had about theoretical "should we use the 10 year old feature of the language". The changes are already available, here in this PR, and in my patch series from like 5 years ag.

It's not a question of "should the change be made?", it's a question of "Is the PR going to be merged?". If you have a complaint about any of the specific changes this PR does, point them out.

Regardless, please re-open the PR, as github won't allow me to.

**Comment by jhasse** [comment]
> It's not a question of "should the change be made?", it's a question of "Is the PR going to be merged?". If you have a complaint about any of the specific changes this PR does, point them out.

For me it is a question of "should the change be made?". And currently my answer is "No.". This PR isn't going to be merged by me because I don't think this change should be made.

**Comment by jonesmz** [comment]
Ok, then re-open it and ignore it like you do with most of the other contributions I submit for review.

When someone else is a maintainer, they'll merge it.

It's not like this patch is going to disappear. I've been maintaining it for years, and it's change #2 in my patch series.

----------------------------------

If you have specific technical complaints, tell me, and I'll promptly address them. Otherwise, I'll continue waiting.

**Comment by jhasse** [comment]
I would prefer it if you open an issue. In this issue you can then link the PR and thus it won't be forgotten.

Ideally the workflow would be:

1. You open an issue.
2. Discussion takes place and it is decided that the change should be made.
3. PR gets created which links the # number of the issue (this will then also show the PR in the discussion of the issue).
4. Discussion on the code change takes place.
5. PR gets merged which will close the issue automatically.

The problem with discussion in PRs is the following: Lets say someone will say "Good change! But I think this should be done in a different way. I will create a new PR." He will then create a new PR, hopefully linking the old one. The old PR gets closed and the discussion continues in the new one. Result: Discussion is scattered all over this place.

This has happened a lot, sometimes even with more than 2 PRs.

Hope this makes it clear to you, why I prefer to have issues instead of PRs in most cases.

**Comment by jonesmz** [comment]
I do understand what you're describing. Generally speaking, I disagree with what you're asking for, but I'm OK with playing along.

It sounds like you're really wanting "Discussions", which is enabled via https://github.com/ninja-build/ninja/settings -> "Discussions" checkbox about 1/2 of the way down the page.

The drawbacks of your proposed workflow is:

1. People who either already have the change in question ready to go, or who would otherwise be willing to make the change, are now discouraged from contributing their code, or potential code, because there is a new task that must be completed before they are "allowed" to open a pull request to demonstrate the changes they want. This can mean people who would have otherwise been willing to contribute an improvement now don't bother.
2. Lots of people who are comfortable submitting pull requests don't even look at the issues because the issues are items that people have a problem about, but no solution for. Pull requests are for the solutions to problems, or general enhancements. This can lead to potential contributors not even realizing that a discussion is taking place in the first place.
3. This adds yet-another-place for the discussion to be scattered across.
4. Dilution of attention where people who are comfortable discussing the actual code changes now have to parse through the peanut gallery of comments from people who aren't making code changes but just talking about issues they are having.
5. This is contrary to the "typical" behavior on github, and there's no mechanism for you to prevent a PR from being opened prior to a discussion reaching the "OK for a pull request" point. There will be plenty of drive-by contributors who don't know that the ninja project prefers an issue be opened for discussion prior to a PR being opened.
6. Per 1. If the discussion takes more than a day (or even an hour, in some cases) many potential contributors will abandon the effort anyway, if the current set of Ninja maintainers aren't able to commit to *prompt* attention on any discussion.

However, since I do want to play by the rules, in the future I'm happy to try to make a new issue (Or preferably a new Discussion as that's the purpose of that feature) *first* before I create a PR -- but not for the following situations:

1. Minor code changes that are obviously an improvement
2. Proposed code changes that can't realistically be implemented in more than one way, preventing the problem of multiple PRs being created for the same topic.
3. Code changes where I've already had the associated commits finished and in use for years.
4. Code changes where any discussion that would take place would almost always need to be in terms of actual changes to the code, and having the proposed changes visually in front of the people having that discussion is necessary to be able to have a meaningful discussion.

Since this PR falls under both 2 and 3. of my list, I'll refer back to my previous request for you to reopen this PR and let another maintainer discuss it with me in the future.

**Comment by jhasse** [comment]
> It sounds like you're really wanting "Discussions", which is enabled via https://github.com/ninja-build/ninja/settings -> "Discussions" checkbox about 1/2 of the way down the page.

I can't do that (not an Owner).

**Comment by jonesmz** [comment]
@evmar @nico empower the active maintainer of the project to make appropriate setting changes.

**Comment by jhasse** [comment]
> People who either already have the change in question ready to go, or who would otherwise be willing to make the change, are now discouraged from contributing their code, or potential code, because there is a new task that must be completed before they are "allowed" to open a pull request to demonstrate the changes they want. This can mean people who would have otherwise been willing to contribute an improvement now don't bother.

IMO that's not a drawback but an advantage, when I remove the assumption you made: "improvement" is always debatable.

**Comment by jonesmz** [comment]
Whether its called an improvement or not, the patch/commit has existed largely unchanged for several years and cannot be meaningfully implemented in a different way other than breaking it into parts, which I've not yet heard anyone ask for me to do.

No productive purpose is served by first opening a new issue before showing people the actual changes being proposed.

For future proposed changes, I'm more open to first making a new issue.

**Pull request closed without merging**
