### PR TITLE
Simplify ComputeCriticalPath() function.

### PR DESCRIPTION
**Pull request by digit-google**
Using simple unordered sets is enough to perform the same computation with less complexity, smaller and faster code.

On a large Fuchsia build plan, this reduces the
ComputeCriticalPath metric from 2.6s to 2.1s!

### CODE REVIEW

**Comment by digit-google** [comment]
Invoking @bradking here too.

**Comment by bradking** [comment]
Since we were not relying on any ordering of `std::set`, switching to `std::unordered_set` should be fine, and C++11 is now allowed AFAIK.

**Comment by digit-google** [comment]
Thanks.

On a related note, I must admit that personally, I find the extra 2.1s a productivity killer for incremental builds (especially since my version of Ninja has [persistent mode](https://fuchsia.dev/fuchsia-src/development/build/ninja_fuchsia_improvements?hl=en) to speed these significantly).

What do you think about adding an option, or environment variable to disable this (not in this PR of course).
@jhasse, do you have an opinion on this?

**Comment by jhasse** [comment]
Thanks!

I agree that 2.1s are still too much. Instead of an option we should fallback to a simpler, naive algorithm above a certain threshold?

**Comment by benoit-pierre** [comment]
> (especially since my version of Ninja has [persistent mode](https://fuchsia.dev/fuchsia-src/development/build/ninja_fuchsia_improvements?hl=en) to speed these significantly).

That `NINJA_STATUS_MAX_COMMANDS` feature to show the status of running commands is really sweet, any plan on upstreaming it?

**Pull request merged**
