### PR TITLE
Add --quiet and -q flags

### PR DESCRIPTION
**Pull request by xyproto**
* Add a `--quiet` and a `-q` flag.
* Also respect the `QUIET` environment variable, if it's set to `1`.
* Makes ninja not print status updates, `Entering directory` or `no work to do`.

See also: #420, #480, #1537, #1818 and #1682

### CODE REVIEW

**Comment by megabyde** [comment]
Any update on this? We have big builds and the CI logs are monstrous with the default mode.

**Comment by jhasse** [comment]
Why did you create a new PR when there are already so many existing ones?

We didn't want `-q` as that means `--question` in Make and might confuse some people. We also don't want to introduce a new envirnoment variable for this, the flag is enough.

**Comment by xyproto** [comment]
@jhasse

The two previous pull requests both have unresolved issues and/or are abandoned. #420 is from September 2012.

`--ask` is often used to avoid naming the flag `--question`. I think `--question` should rather be `--ask`.

`--quiet` in combination with `-q` are very common.

**Comment by jhasse** [comment]
> I think --question should rather be --ask.

I agree, but we can't change that now.

> --quiet in combination with -q are very common.

Yes, but not with Make. And many Ninja users are coming from Make, that's why I think we shouldn't add the short option.

**Comment by xyproto** [comment]
I see that `--question` is used by make, but I don't see why an unconventional use of a flag by `make` should be relevant, as long as `ninja` is not a drop-in replacement for `make`.

Additionally, many developers use `ninja` exclusively via `cmake`.

While many Ninja users may be used to `make`, I like to think they are able to accept and understand that different utilities take different flags.

**Comment by megabyde** [comment]
What about `-s, --silent, --quiet` from `make`?

**Comment by xyproto** [comment]
I believe `--quiet` is much, **much** more common than `--silent`. Here's a data-point from my current system (Arch Linux, various packages installed):

    grep -a -c -l "\-\-silent" /usr/bin/* 2>/dev/null | wc -l
    91
    
    grep -a -c -l "\-\-quiet" /usr/bin/* 2>/dev/null | wc -l
    469
    
While this is not an exact science, I would expect you to get similar results for your systems.

I really believe `make` is the odd one out here, in terms of flag usage, and not a program to emulate.

**Comment by jhasse** [comment]
> I don't see why an unconventional use of a flag by make should be relevant, as long as ninja is not a drop-in replacement for make.

Even if Ninja is not a drop-in replacement for Make, Make is still a lot more important to Ninja than other command line tools.

In general I'm not a fan of one letter options - better be explicit.

**Comment by megabyde** [comment]
What about using `--silent`?

**Comment by jhasse** [comment]
What's wrong with `--quiet` only?

**Comment by xyproto** [comment]
* Both `-q` and `--quiet` are very conventional.
* `ninja` is not `make` and already does not behave exactly like `make` (and why should it?)

I think this patch would be beneficial to Ninja like it is.

**Comment by xyproto** [comment]
Is there any chance that this pull request will be merged, or should I just close it?

**Comment by jhasse** [comment]
Closing in favor of #1968.

**Pull request closed without merging**
