### PR TITLE
unistd.h

### PR DESCRIPTION
**Pull request by HideakiAtsuyo**
I never seen `unistd.h` anywhere  in Windows

### CODE REVIEW

**Comment by HideakiAtsuyo** [comment]
And like this:


```
$ cmake .
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
-- IPO / LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Dev/Ninja/Source/build```

**Comment by slyshykO** [comment]
> 
> 
> I never seen `unistd.h` anywhere in Windows

`unistd.h` is present in gcc toolchains for windows like MinGW and similar

**Comment by HideakiAtsuyo** [comment]
> > I never seen `unistd.h` anywhere in Windows
> 
> `unistd.h` is present in gcc toolchains for windows like MinGW and similar

I have mingw but i don't have `unistd.h` and i have an error just for this so just to be sure i do this PR(and the build is perfect, so it's not needed on windows) \:)

**Comment by okuoku** [comment]
> I have mingw but i don't have `unistd.h`

There are several MinGW libc implementations. MinGW-w64 has one for example.

https://github.com/mirror/mingw-w64/blob/fc2b4752ac61670d6d4940959a78da5ad8a9ebc4/mingw-w64-headers/crt/unistd.h

**Comment by HideakiAtsuyo** [comment]
> > I have mingw but i don't have `unistd.h`
> 
> There are several MinGW libc implementations. MinGW-w64 has one for example.
> 
> https://github.com/mirror/mingw-w64/blob/fc2b4752ac61670d6d4940959a78da5ad8a9ebc4/mingw-w64-headers/crt/unistd.h

Yeah prolly but it's not needed on Windows and the build is a success so why wasting some times by searching it when it's not required :)

**Comment by jhasse** [comment]
> There are several MinGW libc implementations. MinGW-w64 has one for example.

**Comment by HideakiAtsuyo** [comment]
> > There are several MinGW libc implementations. MinGW-w64 has one for example.

Basically i use it but np ;)

**Pull request closed without merging**
