### PR TITLE
Documented -k 0.

### PR DESCRIPTION
**Pull request by orlp**
Solves https://github.com/ninja-build/ninja/issues/1056.

### CODE REVIEW

**Comment by nico** [comment]
Thanks for the patch. I haven't merged it yet because "(0 is unbounded)" sounds a bit awkward to me. I can't think of anything better either though. Maybe someone else out there is good with words and can suggest a wording?

**Comment by nicolasdespres** [comment]
Some of us did suggest alternatives in the comments about #1056.

**Comment by nico** [comment]
That was just the same message instead of "unlimited" instead of "unbounded". That sounds a bit better, but still strange to me. "0 is unlimited" sounds like a statement about the integer 0 to me. "0 means unlimited" works, but isn't really true as the build stops when it can't proceed any more. "keep going; if N > 0 stop after N jobs failed" is maybe ok?

**Comment by nico** [comment]
(has anyone ever used a k parameter that isn't 0? i actually don't know why this gets a parameter. not that i want to change it at this point.)

**Comment by jhasse** [comment]
Superseded by #1373.

**Pull request closed without merging**
