### PR TITLE
Prevent unnecessary reconfig by not writing build.ninja to .ninja_log.

### PR DESCRIPTION
**Pull request by donhinton**
This is a fix to #1376.

### CODE REVIEW

**Comment by jhasse** [comment]
As mentioned in https://github.com/ninja-build/ninja/pull/1527#issuecomment-491315057, I want to fix the bug in a different way.

**Comment by donhinton** [comment]
Will your proposed fix require changes to cmake?

**Comment by jhasse** [comment]
Yes, see https://gitlab.kitware.com/cmake/cmake/merge_requests/3316.

**Comment by donhinton** [comment]
Thanks for the quick response.

I agree your proposal is probably a much cleaner solution, however I’m A
clang/llvm contributor, and we won’t be able to upgrade cmake, currently
using 3.4.3, for a long time, perhaps years.

If you could find an alternative that didn’t require cmake changes, I’d
really appreciate it.

Thanks again for a great tool!

**Comment by jhasse** [comment]
btw: If you don't want to change any flags, you can also build the `rebuild_cache` target.

Why can you upgrade Ninja, but can't upgrade CMake?

**Comment by donhinton** [comment]
I’ll try that, thanks for the hint.

I help maintain the cmake files, and I’ve been burned a few times by using
newer features that aren’t available in 3.4.3 — our buildbots are
maintained by 3rd parties and only get upgraded as needed.

Now I only use the approved version locally so I don’t accidentally
introduce a feature that will break one of the bots.  I’ll be stuck on
3.4.3 for at least another year, and even then, I doubt we’ll upgrade to
the latest and greatest.

**Comment by jhasse** [comment]
I see. You'll be able to call `ninja -t restat` manually after reconfiguring which should prevent the additional reconfig :)

**Comment by donhinton** [comment]
Thanks, but that’s not really a workable solution.   I need something that
works without me having to remember to run some special command.

I’m just going to use my fork which fixes the problem from now on.

Thanks again...

**Comment by Mis1eader-dev** [comment]
Is this not implemented yet?
Personally I have a use case where I copy big C++ projects and perform a `sed` to replace the `./build` directory file contents pointing to the new path, and executing `ninja` on top triggers a reconfigure of CMake and essentially rebuilds the entire thing.

I assume CMake is getting triggered because of the modification time from copying the C++ project directory?

**Comment by jhasse** [comment]
In your usecase it probably happens because the timestamps have changed, see #1459.

**Pull request closed without merging**
