### PR TITLE
Fix pool->current_use_ not being decremented when edges fail

### PR DESCRIPTION
**Pull request by zdave**
eg With this build file...

  pool failpool
    depth = 1
  rule fail
    command = fail
    pool = failpool
  build out1: fail
  build out2: fail
  build out3: fail
  build final: phony out1 out2 out3

...and "-k 0", we should run out1..3 sequentially before failing. Previously we
would fail after just running out1.

### CODE REVIEW

**Comment by sgraham** [comment]
Also in #1017 I think.

**Comment by zdave** [comment]
Ah indeed. Should I just close this?

**Comment by bradking** [comment]
See #1126 which reconciles this with #1017.

**Comment by nico** [comment]
Closing in favor of #1126 (which has your test too).

**Pull request closed without merging**
