### PR TITLE
GitHub Actions: Use CentOS 7 for Linux, fix #1533

### LINKED ISSUE #1533: Ninja 1.9.0, CentOS 7: GLIBCXX symbols not found
**Background**
We build/package our deliverable in a CentOS 7 Docker container that has the minimum-required dependencies for our build. This includes Ninja 1.8.2, which we download directly from GitHub during the image building process:

```bash
# Download the archive
curl -LO .../ninja-linux.zip

# Unarchive it to a location that should already be in the PATH
unzip -d /usr/local/bin ninja-linux.zip
```

I'm investigating upgrading our dependencies (CMake, etc.) and noticed that Ninja is now up to 1.9.0. Before updating my image, I wanted to make sure it wouldn't have any issues building our code, so I spawned a barebones CentOS 7 container, downloaded/unarchived the official Linux binary archive, and ran `ninja --version` to try to verify I'm running 1.9.0.

```bash
# Download the archive
curl -LO .../ninja-linux.zip

# Working locally for demonstration purposes
unzip ninja-linux.zip

# The unarchived file was not executable
chmod +x ninja
```

The following documents/demonstrates the issues I ran into.

**Notes**
- I ran the following commands in the same barebones CentOS 7 Docker container
- I renamed the `ninja` executables according to their respective release version

**Checking the `ninja` version**
```
$ ./ninja-1.8.2 --version
1.8.2

$ ./ninja-1.9.0 --version
./ninja-1.9.0: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./ninja-1.9.0)
./ninja-1.9.0: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./ninja-1.9.0)
```
It seems the official binary was built with symbols that aren't found in the system-provided GCC 4.8.5 `libstdc++.so.6`. Determined via:
```
$ ldd -v ninja-1.9.0
./ninja-1.9.0: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./ninja-1.9.0)
./ninja-1.9.0: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./ninja-1.9.0)
        linux-vdso.so.1 =>  (0x00007ffffd727000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ffb8c86d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffb8c4ac000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffb8c1aa000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffb8cb76000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffb8bf94000)

        Version information:
        ./ninja-1.9.0:
                libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.7) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.15) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
                libstdc++.so.6 (GLIBCXX_3.4.21) => not found
                libstdc++.so.6 (CXXABI_1.3) => /lib64/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.20) => not found
                libstdc++.so.6 (GLIBCXX_3.4) => /lib64/libstdc++.so.6
        /lib64/libstdc++.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                libm.so.6 (GLIBC_2.2.5) => /lib64/libm.so.6
                libgcc_s.so.1 (GCC_4.2.0) => /lib64/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.3) => /lib64/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.0) => /lib64/libgcc_s.so.1
                libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
        /lib64/libm.so.6:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libgcc_s.so.1:
                libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
```

**Comparing `GLIBCXX` references**
From the output, the missing symbols refer to `GLIBCXX_3.4.20` and `GLIBCXX_3.4.21`. Comparing the `GLIBCXX` references between 1.8.2 and 1.9.0 yields the following:

**Ninja 1.8.2**
```
$ readelf -a ninja-1.8.2 | egrep -o '\bGLIBCXX\S+\b' | sort -iu
GLIBCXX_3.4

$ objdump -CT ninja-1.8.2 | grep GLIBCXX
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::append(char const*, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::__throw_length_error(char const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_decrement(std::_Rb_tree_node_base const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::_M_mutate(unsigned long, unsigned long, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::replace(unsigned long, unsigned long, char const*, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator new[](unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator delete(void*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::reserve(unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::find_last_of(char const*, unsigned long, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_decrement(std::_Rb_tree_node_base*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::__throw_out_of_range(char const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(unsigned long, char, std::allocator<char> const&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::_Rep::_M_destroy(std::allocator<char> const&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::find_first_of(char const*, unsigned long, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_increment(std::_Rb_tree_node_base const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::append(unsigned long, char)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::find(char, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::compare(char const*) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::find(char const*, unsigned long, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::assign(char const*, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::assign(std::string const&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator delete[](void*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_increment(std::_Rb_tree_node_base*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::__throw_bad_alloc()
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::resize(unsigned long, char)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator new(unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&, unsigned long, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::_M_leak_hard()
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::string::append(std::string const&)
000000000062c440 g    DO .bss   0000000000000020  GLIBCXX_3.4 std::string::_Rep::_S_empty_rep_storage
000000000062c418 g    DO .bss   0000000000000001  GLIBCXX_3.4 std::string::_Rep::_S_terminal
```

**Ninja 1.9.0**
```
$ readelf -a ninja-1.9.0 | egrep -o '\bGLIBCXX\S+\b' | sort -iu
GLIBCXX_3.4
GLIBCXX_3.4.20
GLIBCXX_3.4.21

$ objdump -CT ninja-1.9.0 | grep GLIBCXX
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::__throw_length_error(char const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.20 std::__throw_out_of_range_fmt(char const*, ...)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator new[](unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator delete(void*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_decrement(std::_Rb_tree_node_base*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_increment(std::_Rb_tree_node_base const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::__throw_logic_error(char const*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator delete[](void*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::_Rb_tree_increment(std::_Rb_tree_node_base*)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 std::__throw_bad_alloc()
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4.21 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)
0000000000000000      DF *UND*  0000000000000000  GLIBCXX_3.4 operator new(unsigned long)
```
The output indicates the name mangling is a bit different, but also that there are new symbols introduced in the 1.9.0 binary compared to the 1.8.2 binary.

If I'm missing something, I'm happy to accept correction/clarification. Thank you for your time.

### PR DESCRIPTION
**Pull request by jhasse**
@nightlark

### CODE REVIEW

**Comment by jhasse** [comment]
Any objections?

**Comment by jonesmz** [comment]
This is to ensure it works properly on an older distribution?

If so, it appears to be a good implementation for that

**Comment by nightlark** [comment]
It's looks like it will work for building a ninja binary linked to an older version (2.17) of glibc. Combined with the static linking to deal with other shared libraries, that should create a binary that works on glibc Linux distros released since 2013 (RHEL 7, Ubuntu 13.04, Debian 8, and Fedora 20).

No objections to merging, it's a step towards more portable release binaries.


Two potential things related to portable Linux binaries which can be addressed later (or not) since they'd be a bit more involved to get working:
- duplication of the workflow/build script and some extra installation steps (7zip) may not be needed; using a docker action for the compilation step would keep the workflows mostly the same for all platforms
- it looks like the Python manylinux1 standard (PEP 513) is based on CentOS 5, which is what the current pip ninja package follows; that is old and getting a newer compiler installed wouldn't be fun

**Comment by jonesmz** [comment]
Is Cent OS 7 (or equivalent) going to represent the minimum supported version of ninja's various dependencies?

**Comment by jhasse** [comment]
Which dependencies?

**Comment by jonesmz** [comment]
Compiler version, standard lib version (not the language standard, but the specific version of the standard library. There's lots of bug fixes that go on in point releases), so on.

**Comment by nightlark** [comment]
At least right now the CentOS 7 build might use the oldest compiler/system libraries out of the regularly run CI builds -- I'm not sure sure it should stay that way though for the release binaries (as mentioned standard lib versions get bug fixes).

**Pull request merged**
