### PR TITLE
disable warning about conditional expressions

### PR DESCRIPTION
**Pull request by fbenkstein**
This fixes a compilation error with ~~VS2010~~ VS2008.

### CODE REVIEW

**Comment by tfarina** [comment]
+ @sgraham just in case.

Do you mind including the error message you have got when building with VS2010 in the commit message?

**Comment by fbenkstein** [comment]
See https://msdn.microsoft.com/en-us/library/6t66728h.aspx.  I believe this warning only exists in VS2010.

**Comment by nico** [comment]
Thanks for the patch! The snippet on https://msdn.microsoft.com/en-us/library/6t66728h.aspx does warn for me with VS2013, but VS2013 doesn't warn when building ninja for me. Can you paste the warning message you're seeing?

**Comment by fbenkstein** [comment]
Here it is:

```
This fixes the following compilation error with VS2010:

cl /showIncludes /nologo /Zi /W4 /WX /wd4530 /wd4100 /wd4706 /wd4512 /wd4800 /wd4702 /wd4819 /wd4355 /wd4091 /GR- /wd4267 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /
D_HAS_EXCEPTIONS=0 /DNINJA_PYTHON="python.exe" /Ox /DNDEBUG /GL -I. -c src\build_log.cc /Fobuild\build_log.obj
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(1179) : error C2220: warning treated as error - no 'object' file generated
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(1171) : while compiling class template member function 'std::_List_nod<_Ty,_Alloc>::_
Node *std::list<_Ty,_Ax>::_Buynode(void)'
        with
        [
            _Ty=std::pair<const StringPiece,BuildLog::LogEntry *>,
            _Alloc=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>,
            _Ax=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>
        ]
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\xhash(205) : see reference to class template instantiation 'std::list<_Ty,_Ax>' being comp
iled
        with
        [
            _Ty=std::pair<const StringPiece,BuildLog::LogEntry *>,
            _Ax=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>
        ]
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\hash_map(88) : see reference to class template instantiation 'stdext::_Hash<_Traits>' bein
g compiled
        with
        [
            _Traits=stdext::_Hmap_traits<StringPiece,BuildLog::LogEntry *,StringPieceCmp,std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>,false
>
        ]
        c:\users\...\projects\ninja\src\build_log.h(88) : see reference to class template instantiation 'stdext::hash_map<_Kty,_Ty,_Tr>' being compiled
        with
        [
            _Kty=StringPiece,
            _Ty=BuildLog::LogEntry *,
            _Tr=StringPieceCmp
        ]
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(1179) : warning C4127: conditional expression is constant
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(1200) : warning C4127: conditional expression is constant
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(1190) : while compiling class template member function 'std::_List_nod<_Ty,_Alloc>::_
Node *std::list<_Ty,_Ax>::_Buynode(std::_List_nod<_Ty,_Alloc>::_Node *,std::_List_nod<_Ty,_Alloc>::_Node *,const _Ty &)'
        with
        [
            _Ty=std::pair<const StringPiece,BuildLog::LogEntry *>,
            _Alloc=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>,
            _Ax=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>
        ]
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(775) : warning C4127: conditional expression is constant
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(732) : see reference to function template instantiation 'void std::list<_Ty,_Ax>::_In
sert<_Iter>(std::list<_Ty,_Ax>::_Const_iterator<_Secure_validation>,_Iter,_Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Ty=std::pair<const StringPiece,BuildLog::LogEntry *>,
            _Ax=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>,
            _Iter=std::list<std::pair<const StringPiece,BuildLog::LogEntry *>,std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>>::_Const_iterato
r<true>,
            _Secure_validation=true
        ]
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(1157) : see reference to function template instantiation 'void std::list<_Ty,_Ax>::in
sert<std::list<_Ty,_Ax>::_Const_iterator<_Secure_validation>>(std::list<_Ty,_Ax>::_Const_iterator<_Secure_validation>,_Iter,_Iter)' being compiled
        with
        [
            _Ty=std::pair<const StringPiece,BuildLog::LogEntry *>,
            _Ax=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>,
            _Secure_validation=true,
            _Iter=std::list<std::pair<const StringPiece,BuildLog::LogEntry *>,std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>>::_Const_iterato
r<true>
        ]
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\list(1126) : while compiling class template member function 'void std::list<_Ty,_Ax>::_Spl
ice(std::list<_Ty,_Ax>::_Const_iterator<_Secure_validation>,std::list<_Ty,_Ax> &,std::list<_Ty,_Ax>::_Const_iterator<_Secure_validation>,std::list<_Ty,_Ax>::_Co
nst_iterator<_Secure_validation>,unsigned __int64,bool)'
        with
        [
            _Ty=std::pair<const StringPiece,BuildLog::LogEntry *>,
            _Ax=std::allocator<std::pair<const StringPiece,BuildLog::LogEntry *>>,
            _Secure_validation=true
        ]

```

I put it into the commit message as well as requested by @tfarina.

**Comment by sgraham** [comment]
"Microsoft Visual Studio 9.0" is VS2008? I'm surprised it builds at all tbh. Or is it possible something is confused and you've got the 2010 compiler with 2008 headers?

**Comment by fbenkstein** [comment]
"The internal version number of Visual Studio 2008 is version 9.0" -- https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#Visual_Studio_2008

I'm working on an integration with Python and Python 2.7 is still on VS2008 so it is kinda relevant.

**Comment by sgraham** [comment]
OK, if it works, it seems fine to disable the warning. Just your description said VS2010, so I was confused.

**Comment by fbenkstein** [comment]
Yes, I got confused myself.  Will update the commit message.

**Comment by fbenkstein** [comment]
I dug a little bit deeper and included my findings in the commit message.

**Comment by nico** [comment]
Thanks for the log and explanation. I too am a bit surprised building with 2008 works at all :-)

**Pull request merged**
