### PR TITLE
miniscule grammar fix in documentation

### PR DESCRIPTION
**Pull request by rjindael**
"If you do this work" -> "If this works for you"

### CODE REVIEW

**Comment by jonesmz** [comment]
I think that the point of that sentence was to ask the people who convert build system generators to use ninja to tell the ninja project.

I don't think that the goal of the sentence was to ask people to tell the ninja project about random build tools that happen to work with ninja, as there wouldn't be any that would.

**Comment by rjindael** [comment]
"if you do this work" still doesn't make any grammatical sense

**Comment by jonesmz** [comment]
"If you do this work", aka "If you do the work to adapt a build system to use ninja"

**Comment by jhasse** [comment]
"work" is used as a noun, for me it makes sense.

I'm not a native speaker, but I still believe this has a different meaning than "If you find one that works".

**Pull request closed without merging**
