### PR TITLE
std:: corrections

### PR DESCRIPTION
**Pull request by kvart2006**
I made these changes because on NetBSD the compiler asks them.
I replaced "naked" string, map etc. by std::string, std::map etc.
./configure.py --bootstrap works!

### CODE REVIEW

**Comment by kvart2006** [comment]
I only changed in string_piece.h:
std::size_t .

**Comment by nico** [comment]
Thanks for the patch! Can you show an example of the compiler diagnostic? There are `using namespace std` statements in a few places, so compilers should be happy.

**Comment by ilyapopov** [comment]
Looks like this is because there are `using namespace std;` in headers, which is considered bad practice.

**Comment by nico** [comment]
Closing since my question didn't get an answer.

**Pull request closed without merging**
