### PR TITLE
cmake: add BUILD_TESTING option (ON by default)

### PR DESCRIPTION
**Pull request by ledocc**
option provided by cmake's buildin Module CTest
enable_testing() is call by this Module

### CODE REVIEW

**Comment by scivision** [comment]
Thank you!  It is nice to use the canonical option as you have done vs. #1838.

My use case is building software suite natively on embedded systems, and one of the first steps is building Ninja, which uses too much RAM when ninja_test is built. And I don't want to built test suites for any of the suite to save time on a puny CPU. 
The users are engineers / scientists. The idea is to have a standalone system where the user doesn't need to setup a cross-compile toolchain when they might never or only once use it.

**Comment by jhasse** [comment]
Thanks! While I went with tabs in CMakeLists.txt I think it makes more sense to follow the style of the rest of Ninja's source. Can you convert the tabs to 2 spaces in the lines you've touched?

**Comment by ledocc** [comment]
For the "TAB or space" choice, I prefer space. But I follow the CMakeLists.txt style.
I can convert tabs to 2 spaces. But only for lines I have touch? This will mix tab an space in the same file.
Will be better to change all tabs to 2 space in a separate commit, isn't it ?

**Comment by jhasse** [comment]
> But only for lines I have touch? 

Yes. I want to avoid a dedicated commit. I think there's already a mixture in the file.

**Comment by ledocc** [comment]
done !

**Pull request merged**
