### PR TITLE
Add "environment" as a special attribute

### PR DESCRIPTION
**Pull request by sgraham**
Oops, forgot to click pull.

This optionally sets the environment block for Windows subprocesses. Do you think this is a reasonable approach to getting rid of the wrapper on win?

### CODE REVIEW

**Comment by nico** [comment]
I always said that I thought just setting the env via e.g. `ninja -t msvc -e` would be fine, but iirc @ngladitz collected data for me that shows that the subprocess overhead from that is actually measurable. (I think that data is still in a tab on another computer, but I can't find it now.) So this might be something we might want to do in the future, but it's a bit messy and the win wasn't _that_ huge iirc. But let's keep this open for now.

**Comment by nico** [comment]
Here's the link ngladitz sent me: https://github.com/ngladitz/cmake/commits/ninja-cl-deps-performance

**Comment by martine** [comment]
I suspect if we went down the route of the inline environment block we'd run into requests for:
- a way to express just additions/removals to the outer environment
- a more convenient way to express them than as a long block of `foo$0bar$0baz$0$0`
Perhaps we can punt both of those to just say it's the generator's problem, though.

This is a longer way of saying: it'd be nice to collect all the requirements of users before we commit to any new feature.

**Comment by jhasse** [comment]
Closing due to merge conflicts. If you still think this is relevant, feel free to reopen :)

**Pull request closed without merging**
