### PR TITLE
Remove 'using namespace std', properly namespace all std symbols

### PR DESCRIPTION
**Pull request by jonesmz**
I'm creating a fork of Ninja that focuses on keeping the source as close as possible with the Ninja code, but incorporates c++17-isms where ever I think it's practical.

So really it's a patch series, but github is an awful medium for doing that without making a fork and committing on top of it. It is what it is, I guess.

The first change is to properly namespace std::symbols.

I'm sure my motivation for doing that isn't really something that the Ninja maintainers care about, since it's one of those tabs vs spaces kinds of discussion that ultimately boils down to be mostly about personal preference, but suffice to say it's the first and by far the largest patch, and I'm not going to drop it from my patch series. shrug.

I hope that you'll be willing to merge it, as it'll drastically reduce the amount of work I have to do to continue incorporating changes from upstream into my patch series, but if you don't want to merge this pull request please don't feel that you should leave this pull request open. I'd rather rip the band-aid off quickly.

### CODE REVIEW

**Comment by jonesmz** [comment]
It looks like AppVeyor is having difficulty running the unit tests, but I can't see how my changes would have effected them...

**Comment by jonesmz** [comment]
It's been 2 months.

Can I get a hint?

**Comment by nico** [comment]
Thanks for the patch, but the current code looks like it does intentionally.

See also the old "Can't build ninja with clang++ against libc++" thread on the mailing list for a discussion of this.

**Comment by jonesmz** [comment]
Thank you for replying to my pull request.

I do not appreciate the 3 month delay for such a simple response.

I also don't appreciate you referencing an (un-hyperlinked) mailing list thread from 4 years ago where 90% of the postings were saying you are wrong with evidence from widely recognized community experts, and evidence of platforms where your decision to use "using namespace std" caused compile errors on valid and commonly used platforms.

Your rationale essentially boils down to "its fine how it is", and you provide no other explanation or justification.

Please reconsider your behavior as a maintainer of ninja-build.

Personally I don't think you're doing a good job.

Ways you can improve:

Respond to pull requests within 1 month. Use technical justifications for your decisions, especially in the face of diverse community opposition. Provide at least some transparency for nontechnical decisions like style and language version.

**Pull request closed without merging**
