### PR TITLE
Add clang-analyze to build

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by jhasse** [comment]
I think clang-tidy runs the analyzer, too, right? See #1768.

**Comment by jonesmz** [comment]
Apparently it can, I didn't know that.

But it requires the specific clang-analyze functionality to be enabled.

Further, it looks like most clang-analyze checks aren't supported by clang-tidy:
https://clang-analyzer.llvm.org/available_checks.html
https://clang.llvm.org/extra/clang-tidy/checks/list.html

I count 11 non-OSX checks in clang-tidy, and over 25 non-OSX checks in clang-analyze.

**Comment by jhasse** [comment]
Ah okay, than running the clang-analyze, too, seems a good idea. When does it run though? The output doesn't help me. Are you sure it would find something (and the GitHub Action check would fail)?

**Comment by jonesmz** [comment]
The "scan-build" command inter-poses the clang-analyzer as a CC and CXX, runs the analysis, and then calls the "real" compiler.

In this case, it doesn't appear that the default-enabled checks are finding anything to complain about, but other projects I work with the default checks do complain.

Do you have any specific checks that you'd like enabled?

**Comment by jhasse** [comment]
No, the default is fine :)

**Pull request merged**
