### PR TITLE
Fix invalid preprocessor #if

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by jhasse** [comment]
Should not make difference since `_WIN32` is defined to 1, right?

**Comment by jonesmz** [comment]
Causes warnings on my compiler (gcc 9.2)

**Comment by jhasse** [comment]
Interesting

**Comment by jonesmz** [comment]
If the value isn't defined, using #if is invalid (needs to be #ifdef). So gcc warns, and says that it assumes the value must be zero.

**Pull request merged**
