### PR TITLE
Supporting OS400 system

### PR DESCRIPTION
**Pull request by zheddie**
This fix is to make ninja support on IBM i OS for "pip install". Please kindly help to review and merge. thanks.

### CODE REVIEW

**Comment by zheddie** [comment]
@jhasse , Hello, can you help to review this PR ? Thanks.

**Comment by jonesmz** [comment]
You should just use the cmake build script. Configure.py is deprecated.

**Comment by zheddie** [comment]
thanks @jonesmz . I notice that the python package :https://github.com/scikit-build/ninja-python-distributions are still using the configure.py. With this fix , we can make the ninja python package works on our system. Can you help to merge it , if it does not break any other feature/system? thanks.

**Comment by jonesmz** [comment]
I am not a maintainer, so I don't have the ability to merge pull requests.

I strongly discourage making changes to configure.py that aren't also done to cmakelists.txt (if needed) though.

**Comment by jhasse** [comment]
We can't test these changes and I'm against supporting closed source operation systems / software whenever possible (at least when I'm not getting paid). Sorry.

**Comment by jonesmz** [comment]
@zheddie 

Your path forward with this is *probably* to submit a fix to the scikit-build/ninja-python-distributions project to use cmake, instead of configure.py.

CMake, assuming it supports `IBM i OS` or `OS400`, will then let you use ninja for your platform without needing changes to the Ninja codebase.

**Comment by jonesmz** [comment]
> CMake, assuming it supports IBM i OS or OS400, will then let you use ninja for your platform without needing changes to the Ninja codebase.

More closely reviewing the cmake code demonstrates that the Ninja project does support building for OS400 with CMake.

For what it's worth, I agree with jhasse that supporting OS400 is not the Ninja project's problem, and I object to special affordances in the CMakeLists.txt file, but the support is there today anyway.

**Comment by zheddie** [comment]
@jonesmz thanks for your comments and explanation. I would try that way.

**Pull request closed without merging**
