### PR TITLE
Split headers into the `include` directory and make them installable

### PR DESCRIPTION
**Pull request by ken-matsui**
I moved all headers except `getopt.h` into the `include` directory for anyone using Ninja as a library.
Since moving `getopt.h` into the `include` directory brought a conflicting declaration, I keep it in the `src` directory:
https://github.com/ken-matsui/ninja/runs/6900527805?check_suite_focus=true#step:6:30

In `CMakeLists.txt`, I replaced some indentations that are written as spaces with tabs.
Also, I could not build dynamic libraries, so I put them commented out. Someone can fix that.

This `CMakeLists.txt` installs the following:

```console
-- Install configuration: ""
-- Installing: /usr/local/include
-- Installing: /usr/local/include/ninja
-- Installing: /usr/local/include/ninja/edit_distance.h
-- Installing: /usr/local/include/ninja/graphviz.h
-- Installing: /usr/local/include/ninja/manifest_parser.h
-- Installing: /usr/local/include/ninja/version.h
-- Installing: /usr/local/include/ninja/status.h
-- Installing: /usr/local/include/ninja/build_log.h
-- Installing: /usr/local/include/ninja/hash_map.h
-- Installing: /usr/local/include/ninja/dyndep_parser.h
-- Installing: /usr/local/include/ninja/includes_normalize.h
-- Installing: /usr/local/include/ninja/clean.h
-- Installing: /usr/local/include/ninja/dyndep.h
-- Installing: /usr/local/include/ninja/exit_status.h
-- Installing: /usr/local/include/ninja/build.h
-- Installing: /usr/local/include/ninja/parser.h
-- Installing: /usr/local/include/ninja/clparser.h
-- Installing: /usr/local/include/ninja/depfile_parser.h
-- Installing: /usr/local/include/ninja/test.h
-- Installing: /usr/local/include/ninja/missing_deps.h
-- Installing: /usr/local/include/ninja/string_piece.h
-- Installing: /usr/local/include/ninja/eval_env.h
-- Installing: /usr/local/include/ninja/graph.h
-- Installing: /usr/local/include/ninja/msvc_helper.h
-- Installing: /usr/local/include/ninja/deps_log.h
-- Installing: /usr/local/include/ninja/string_piece_util.h
-- Installing: /usr/local/include/ninja/json.h
-- Installing: /usr/local/include/ninja/load_status.h
-- Installing: /usr/local/include/ninja/util.h
-- Installing: /usr/local/include/ninja/lexer.h
-- Installing: /usr/local/include/ninja/disk_interface.h
-- Installing: /usr/local/include/ninja/metrics.h
-- Installing: /usr/local/include/ninja/browse.h
-- Installing: /usr/local/include/ninja/state.h
-- Installing: /usr/local/include/ninja/subprocess.h
-- Installing: /usr/local/include/ninja/debug_flags.h
-- Installing: /usr/local/include/ninja/timestamp.h
-- Installing: /usr/local/include/ninja/line_printer.h
-- Installing: /usr/local/include/ninja/win32port.h
-- Installing: /usr/local/lib/libninja-re2c.a
-- Installing: /usr/local/lib/libninja.a
-- Installing: /usr/local/bin/ninja
```

### CODE REVIEW

**Comment by jonesmz** [comment]
Beautiful. I've wanted this for ages.

Could you later do a second pull request that changes `#include "whateverheader.h"` to `#include <ninja/whateverheader.h>" and adjust the cmakelists.txt to only add the "include" folder, and not "include/ninja" ? that would make it much easier to reliably consume ninja as a library, whether as part of the same build tree, or imported from the filesystem.

You could do that with this PR if you wanted to, but chances are that would be too many changes to too many files, and it would delay the review unnecessarily.

**Comment by jhasse** [comment]
Switching between header and source files now becomes more complicated. Unfortunately C++ doesn't have a perfect solution for this (yet) AFAIK.

If the headers are installed anyway, why do we need to move them in Git?

**Comment by jonesmz** [comment]
Could you explain what's more complicated about switching between header and source files? What IDE are you using where this change would make that more difficult?

I find it very annoying to work with projects that have the "public" headers as part of the source directory that cpp files live in. It's a huge code smell and makes consuming the code as a library as part of a larger build tree much more difficult and fragile.

**Comment by jhasse** [comment]
They aren't in the same directory and some tools just look there.

**Comment by jonesmz** [comment]
> They aren't in the same directory 

That's the point...

> and some tools just look there.

Which tools are exhibiting this behavior? It's incorrect, but probably easily configurable.

**Comment by hadrielk** [comment]
> In CMakeLists.txt, I replaced some indentations that are written as spaces with tabs.

Why would you do that? Tabs are different widths in different editor settings, as I'm sure you well know. The whole point of using spaces is so everyone sees them the same way, and things line up cleanly for everyone.

If you don't like the current indentation, why not just add the number of spaces you think look better?

**Comment by hadrielk** [comment]
> If the headers are installed anyway, why do we need to move them in Git?

For private headers, or headers in a project that isn't meant to be used as a library, I'm in total agreement with you. The header should be where its source is. It's far more convenient for developers that way.

But for things meant to be used as libraries, separating the public header into an `include/` folder makes sense because:
1. that way consumers know what's public vs. not very easily
2. their CMake/whatever can limit their using code's visibility/access to just that directory, so they cannot accidentally do `#include <ninja/private.h>`, because it won't be in their include-path.
3. some install scripts copy or symlink the public includes, and making it a directory makes that easier.

**Pull request closed without merging**
