### PR TITLE
CMake: Add support for "browse" mode

### LINKED ISSUE #1822: CMake build doesn't support the browse tool
Enabling the browse requires additional logic to inline the `browse.py` into Ninja which is currently only supported by `configure.py` and not by the CMake build.

### PR DESCRIPTION
**Pull request by aharrison24**
Fixes #1822
Closes #1853

Adds support for `ninja -t browse` to CMake builds.

Browse mode requires a number of POSIX features to be available.
This commit adds configure-time checks that the 'unistd.h' header is
available and that the `inline.sh` script executes successfully. If the
checks pass then browse mode is enabled.

As discussed in #1853, when built via CMake the `ninja` executable
looks for a binary called `python` in the current path, in order to
launch the "browse" mode. The behaviour differs from that of the
configure.py script, which looks for a python executable that has the
*same name* as the python executable that invoked the configure script.

### CODE REVIEW

**Comment by aharrison24** [comment]
Sorry, this obviously isn't ready to go. I'll look in to the CI failures.

**Comment by jhasse** [comment]
Thx!

Instead of adding a list of unsupported operation systems, wouldn't a check for `unistd.h` work? I have no idea why SunOS and AIX aren't supported though.

**Comment by alastair-harrison-oxb** [comment]
Yeah, I wasn't really sure what the reason for some platforms being unsupported was. So I just duplicated the logic from the configure script.

If what it comes down to is OS support for POSIX stuff like `execvp` and `fork` then we could instead use `try_compile` to determine whether those functions are available. Then only enable 'browse' mode if it looks like it will compile properly. I don't know if that would actually buy us much over just checking for `unistd.h`. Although I guess a check for `unistd.h` would also best be done in a `try_compile` command, since we can't be sure exactly where it might live.

**Comment by aharrison24** [comment]
OK, I've taken a crack at doing some more robust platform checks before 'browse' mode is enabled. I did need to modify the `inline.sh` script so that it would return a non-zero exit code if any of its steps failed. I hope that's a reasonable change.

**Comment by jhasse** [comment]
Looks good, thanks!

**Pull request merged**
