### PR TITLE
More constification

### PR DESCRIPTION
**Pull request by Hi-Angel**
Some more of the constification work that I've done this weekend.

I'm a bit unclear and neutral on how to handle best the order of commits here. For example I can squash all `build.cc` commits. Suggestions are welcome.

### CODE REVIEW

**Comment by Hi-Angel** [comment]
Okay, made fix for a CI that uses ancient standards.

**Comment by Hi-Angel** [comment]
Ok, last error is an unrelated problem in CI script.

**Comment by jhasse** [comment]
Can you rebase on master? CI should then succeed.

**Comment by Hi-Angel** [comment]
Sorry, I saw the notification, but somehow I completely forgotten about it! Rebased.

**Comment by Hi-Angel** [comment]
I'm afraid rebasing didn't help, CI still fails for unrelated reason,  this time it's:

```haskell
unable to access 'https://github.com/ninja-build/ninja.git/': Failed to connect to github.com port 443: Timed out
```

**Comment by jhasse** [comment]
AppVeyor bug ;)

Thanks!

**Pull request merged**
